version: 0.0

os: linux

files:
  - source: /
    destination: /var/www/service/stringer

hooks:

  AfterInstall:
    - location: aws/install_ec2/setup_stringer.sh
      timeout: 300
      runas: ubuntu
    - location: aws/install_ec2/setup_nginx.sh
      timeout: 300
      runas: ubuntu
