version: 0.0

phases:
  install:
    commands:
     - pip install -r requirements.txt
  build:
    commands:
      - pytest test

artifacts:
  files:
    - aws/install_ec2/**/*
    - test/**/*
    - stringer/**/*
    - permutations_app.py
    - requirements.txt
    - appspec.yml
    - README.md
