version: 0.2

phases:
  install:
    commands:
     - pip install -r requirements.txt
  build:
    commands:
      - pytest test

artifacts:
  files:
    - test/**/*
    - stringer/**/*
    - permutations_cli.py
    - permutations_app.py
    - log_redaction_cli.py
    - requirements.txt
    - README.md
