AWSTemplateFormatVersion: "2010-09-09"
Description: IAM roles and policies for stringer and wordsum.

Resources:

  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      RoleName: "stringer-instance"

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      InstanceProfileName: "stringer-instance"
      Roles:
        -
          Ref: InstanceRole
