AWSTemplateFormatVersion: "2010-09-09"

Description: Template to create the policies for stringer.

Parameters:

  CodeBuildRoleName:
    Default: codebuild-service-role
    Description: The bucket name
    Type: String

  InstanceRoleName:
    Default: stringer-instance-role
    Description: The role the instance need to read the bucket.
    Type: String

Resources:

  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: stringer-cb-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
          -
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: "*"
          -
            Effect: Allow
            Resource: "*"
            Action:
              - s3:PutObject
            Resource: "*"
          -
            Effect: Allow
            Action:
              - ssm:GetParameters
            Resource: "*"
      Roles:
        -
          Ref: CodeBuildRoleName


  CodeDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: stringer-cd-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:Get*,
              - s3:List*
            Resource: "*"

      Roles:
        -
          Ref: InstanceRoleName

