AWSTemplateFormatVersion: "2010-09-09"

Description: Template for the s3 buckets required by the application.

Parameters:

  BuildBucketName:
    Default: REPLACE_BUILD_BUCKET_NAME
    Description: The bucket name
    Type: String


Resources:

  BuildBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        Ref: BuildBucketName
      AccessControl: Private