AWSTemplateFormatVersion: "2010-09-09"

Description: Template to create the policies for stringer.

Parameters:

  CodeBuildServiceRoleName:
    Default: codebuild-service-role
    Description: The bucket name
    Type: String

  CodeDeployServiceRoleName:
    Default: codedeploy-service-role
    Description: The bucket name
    Type: String


  InstanceRoleName:
    Default: stringer-instance-role
    Description: The role the instance need to read the bucket.
    Type: String

Resources:

  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: stringer-cb-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
          -
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: "*"
          -
            Effect: Allow
            Resource: "*"
            Action:
              - s3:PutObject
            Resource: "*"
          -
            Effect: Allow
            Action:
              - ssm:GetParameters
            Resource: "*"
      Roles:
        -
          Ref: CodeBuildServiceRoleName


  CodeDeployServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: stringer-cd-service-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - autoscaling:CompleteLifecycleAction
              - autoscaling:DeleteLifecycleHook
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeLifecycleHooks
              - autoscaling:PutLifecycleHook
              - autoscaling:RecordLifecycleActionHeartbeat
              - autoscaling:CreateAutoScalingGroup
              - autoscaling:UpdateAutoScalingGroup
              - autoscaling:EnableMetricsCollection
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribePolicies
              - autoscaling:DescribeScheduledActions
              - autoscaling:DescribeNotificationConfigurations
              - autoscaling:DescribeLifecycleHooks
              - autoscaling:SuspendProcesses
              - autoscaling:ResumeProcesses
              - autoscaling:AttachLoadBalancers
              - autoscaling:PutScalingPolicy
              - autoscaling:PutScheduledUpdateGroupAction
              - autoscaling:PutNotificationConfiguration
              - autoscaling:PutLifecycleHook
              - autoscaling:DescribeScalingActivities
              - autoscaling:DeleteAutoScalingGroup
              - ec2:DescribeInstances
              - ec2:DescribeInstanceStatus
              - ec2:TerminateInstances
              - tag:GetTags
              - tag:GetResources
              - sns:Publish
              - cloudwatch:DescribeAlarms
              - cloudwatch:PutMetricAlarm
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeInstanceHealth
              - elasticloadbalancing:RegisterInstancesWithLoadBalancer
              - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
              - elasticloadbalancing:DescribeTargetGroups
              - elasticloadbalancing:DescribeTargetHealth
              - elasticloadbalancing:RegisterTargets
              - elasticloadbalancing:DeregisterTargets
            Resource: "*"

      Roles:
       -
        Ref: CodeDeployServiceRoleName


  CodeDeployInstancePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:  stringer-cd-instance-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:ListBucket
            Resource: "*"

      Roles:
       -
        Ref: InstanceRoleName