AWSTemplateFormatVersion: "2010-09-09"

Description: The code deployment application.

Parameters:

  ServiceRole:
    Default: INPUT_IAM
    Description: IAM service role for code deploy
    Type: String

  ApplicationName:
    Default: stringer-app
    Type: String

  EC2TagKey:
    Default: owner
    Type: String

  EC2TagValue:
    Default: kalab
    Type: String

Resources:

  Application:
    Type: 'AWS::CodeDeploy::Application'
    Properties:
      ApplicationName:
        Ref: ApplicationName

  DeploymentGroup:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName:
        Ref: Application
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      AutoRollbackConfiguration:
        Enabled: 'false'
      DeploymentGroupName: stringer
      Ec2TagFilters:
        - Key:
            Ref: EC2TagKey
          Value:
            Ref: EC2TagValue
          Type: KEY_AND_VALUE
      ServiceRoleArn:
        Ref: ServiceRole