AWSTemplateFormatVersion: "2010-09-09"

Description: The code deployment application.

Parameters:

  ServiceRoleArn:
    Default: REPLACE_ARN_ROLE
    Description: EC2 instance role as it will be used by code deploy.
    Type: String

  ApplicationName:
    Default: stringer-app
    Type: String

  BuildBucketName:
    Default: stringer-test-02
    Description: The bucket name
    Type: String

  EC2TagKey:
    Default: owner
    Type: String

  EC2TagValue:
    Default: kalab
    Type: String

Resources:

  Application:
    Type: 'AWS::CodeDeploy::Application'
    Properties:
      ApplicationName:
        Ref: ApplicationName

  StringerDeploymentGroup:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName:
        Ref: Application
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      Deployment:
        Description: "Deploying Stringer."
        IgnoreApplicationStopFailures: true
        Revision:
          RevisionType: S3
          S3Location:
            Bucket:
             Ref: BuildBucketName
            Key: stringer
            BundleType: Zip
      DeploymentGroupName: stringer
      Ec2TagFilters:
        - Key:
            Ref: EC2TagKey
          Value:
            Ref: EC2TagValue
          Type: KEY_AND_VALUE
      ServiceRoleArn:
        Ref: ServiceRoleArn