AWSTemplateFormatVersion: "2010-09-09"

Description: Begining s3 template to configure and create for this app.

Parameters:

  BucketName:
    Default: REPLACE_WITH_VALUE
    Description: The bucket name
    Type: String


Resources:

  BuildBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        Ref: BucketName
      AccessControl: Private